type AdditionalSeedDinosaur = {
  id: string;
  scientificName: string;
  pbdbName: string;
  fallbackNameJa: string;
  meaning: string;
  clade: 'Saurischia' | 'Ornithischia';
  subgroup: string;
  diet: 'Carnivore' | 'Herbivore' | 'Omnivore';
  region: string;
  lengthMeters: number;
  massEstimateKg: number;
};

function seed(
  id: string,
  scientificName: string,
  fallbackNameJa: string,
  meaning: string,
  clade: AdditionalSeedDinosaur['clade'],
  subgroup: string,
  diet: AdditionalSeedDinosaur['diet'],
  region: string,
  lengthMeters: number,
  massEstimateKg: number,
): AdditionalSeedDinosaur {
  return {
    id,
    scientificName,
    pbdbName: scientificName,
    fallbackNameJa,
    meaning,
    clade,
    subgroup,
    diet,
    region,
    lengthMeters,
    massEstimateKg,
  };
}

export const additionalSeedDinosaurs: AdditionalSeedDinosaur[] = [
  seed('neovenator-salerii', 'Neovenator salerii', 'ネオヴェナトル', '新しい狩人', 'Saurischia', 'Theropoda', 'Carnivore', 'Europe', 7.5, 1000),
  seed('aerosteon-riocoloradensis', 'Aerosteon riocoloradensis', 'アエロステオン', '空気を宿す骨', 'Saurischia', 'Theropoda', 'Carnivore', 'South America', 9, 1500),
  seed('irritator-challengeri', 'Irritator challengeri', 'イリタトル', '苛立たせるもの', 'Saurischia', 'Theropoda', 'Carnivore', 'South America', 8, 1000),
  seed('ichthyovenator-laosensis', 'Ichthyovenator laosensis', 'イクチオヴェナトル', '魚を狩る狩人', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 8.5, 1100),
  seed('eustreptospondylus-oxoniensis', 'Eustreptospondylus oxoniensis', 'エウストレプトスポンディルス', 'よく曲がる脊椎', 'Saurischia', 'Theropoda', 'Carnivore', 'Europe', 6.5, 500),
  seed('masiakasaurus-knopfleri', 'Masiakasaurus knopfleri', 'マシアカサウルス', '凶悪なトカゲ', 'Saurischia', 'Theropoda', 'Carnivore', 'Africa', 2.2, 25),
  seed('rajasaurus-narmadensis', 'Rajasaurus narmadensis', 'ラジャサウルス', '王のトカゲ', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 7.6, 700),
  seed('indosuchus-raptorius', 'Indosuchus raptorius', 'インドスクス', 'インドのワニもどき', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 7, 900),
  seed('skorpiovenator-bustingorryi', 'Skorpiovenator bustingorryi', 'スコルピオヴェナトル', 'サソリの狩人', 'Saurischia', 'Theropoda', 'Carnivore', 'South America', 6, 350),
  seed('abelisaurus-comahuensis', 'Abelisaurus comahuensis', 'アベリサウルス', 'アベルのトカゲ', 'Saurischia', 'Theropoda', 'Carnivore', 'South America', 8.5, 1200),
  seed('noasaurus-leali', 'Noasaurus leali', 'ノアサウルス', '北西アルゼンチンのトカゲ', 'Saurischia', 'Theropoda', 'Carnivore', 'South America', 3, 30),
  seed('saurornitholestes-langstoni', 'Saurornitholestes langstoni', 'サウロルニトレステス', 'トカゲ鳥の盗賊', 'Saurischia', 'Theropoda', 'Carnivore', 'North America', 2, 20),
  seed('sinornithosaurus-millenii', 'Sinornithosaurus millenii', 'シノルニトサウルス', '中国の鳥トカゲ', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 1.2, 5),
  seed('balaur-bondoc', 'Balaur bondoc', 'バラウル', 'ずんぐりした竜', 'Saurischia', 'Theropoda', 'Carnivore', 'Europe', 1.8, 25),
  seed('austroraptor-cabazai', 'Austroraptor cabazai', 'アウストロラプトル', '南の略奪者', 'Saurischia', 'Theropoda', 'Carnivore', 'South America', 5, 350),
  seed('struthiomimus-altus', 'Struthiomimus altus', 'ストルティオミムス', 'ダチョウもどき', 'Saurischia', 'Theropoda', 'Omnivore', 'North America', 4, 150),
  seed('gigantoraptor-erlianensis', 'Gigantoraptor erlianensis', 'ギガントラプトル', '巨大な略奪者', 'Saurischia', 'Theropoda', 'Omnivore', 'Asia', 8, 1400),
  seed('citipati-osmolskae', 'Citipati osmolskae', 'キティパティ', '火葬場の主', 'Saurischia', 'Theropoda', 'Omnivore', 'Asia', 3, 80),
  seed('caudipteryx-zoui', 'Caudipteryx zoui', 'カウディプテリクス', '尾の羽', 'Saurischia', 'Theropoda', 'Omnivore', 'Asia', 1, 5),
  seed('ceratosuchops-inferodios', 'Ceratosuchops inferodios', 'ケラトスクコプス', '角のあるワニ顔', 'Saurischia', 'Theropoda', 'Carnivore', 'Europe', 8, 1200),
  seed('riparovenator-milnerae', 'Riparovenator milnerae', 'リパロヴェナトル', '川岸の狩人', 'Saurischia', 'Theropoda', 'Carnivore', 'Europe', 8.5, 1300),
  seed('siats-meekerorum', 'Siats meekerorum', 'シアッツ', '人食いの怪物', 'Saurischia', 'Theropoda', 'Carnivore', 'North America', 10, 4000),
  seed('deltadromeus-agilis', 'Deltadromeus agilis', 'デルタドロメウス', '三角州を走るもの', 'Saurischia', 'Theropoda', 'Carnivore', 'Africa', 8, 1000),
  seed('megaraptor-namunhuaiquii', 'Megaraptor namunhuaiquii', 'メガラプトル', '巨大な略奪者', 'Saurischia', 'Theropoda', 'Carnivore', 'South America', 8, 1000),
  seed('fukuiraptor-kitadaniensis', 'Fukuiraptor kitadaniensis', 'フクイラプトル', '福井の略奪者', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 4.2, 300),
  seed('yutyrannus-huali', 'Yutyrannus huali', 'ユティラヌス', '美しい羽毛の暴君', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 9, 1400),
  seed('sinocalliopteryx-gigas', 'Sinocalliopteryx gigas', 'シノカリオプテリクス', '中国の美しい羽', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 2.4, 20),
  seed('monolophosaurus-jiangi', 'Monolophosaurus jiangi', 'モノロフォサウルス', '一つの冠を持つトカゲ', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 5.5, 475),
  seed('metriacanthosaurus-parkeri', 'Metriacanthosaurus parkeri', 'メトリアカントサウルス', '適度な棘のトカゲ', 'Saurischia', 'Theropoda', 'Carnivore', 'Asia', 8, 1000),
  seed('afrovenator-abakensis', 'Afrovenator abakensis', 'アフロヴェナトル', 'アフリカの狩人', 'Saurischia', 'Theropoda', 'Carnivore', 'Africa', 8, 1000),

  seed('jobaria-tiguidensis', 'Jobaria tiguidensis', 'ジョバリア', 'ティギド地方のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Africa', 18, 19000),
  seed('bajadasaurus-pronuspinax', 'Bajadasaurus pronuspinax', 'バハダサウルス', 'バハダのトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'South America', 13, 4000),
  seed('nigersaurus-taqueti', 'Nigersaurus taqueti', 'ニジェールサウルス', 'ニジェールのトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Africa', 9, 2000),
  seed('rebbachisaurus-garasbae', 'Rebbachisaurus garasbae', 'レバキサウルス', 'レバキサ地方のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Africa', 14, 7500),
  seed('dicraeosaurus-hansemanni', 'Dicraeosaurus hansemanni', 'ディクラエオサウルス', '二股の梁のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Africa', 13, 5000),
  seed('barapasaurus-tagorei', 'Barapasaurus tagorei', 'バラパサウルス', '大きな脚のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Asia', 14, 7000),
  seed('omeisaurus-junghsiensis', 'Omeisaurus junghsiensis', 'オメイサウルス', '峨眉山のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Asia', 20, 10000),
  seed('bellusaurus-sui', 'Bellusaurus sui', 'ベルサウルス', '美しいトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Asia', 5, 1000),
  seed('wintonotitan-wattsi', 'Wintonotitan wattsi', 'ウィントノティタン', 'ウィントンの巨人', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Australia', 15, 9000),
  seed('austrosaurus-mckillopi', 'Austrosaurus mckillopi', 'アウストロサウルス', '南のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Australia', 15, 12000),
  seed('janenschia-robusta', 'Janenschia robusta', 'ヤネンシア', '頑丈な体格', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Africa', 18, 10000),
  seed('tastavinsaurus-sanzi', 'Tastavinsaurus sanzi', 'タスタヴィンサウルス', 'タスタヴィンス川のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Europe', 12, 5000),
  seed('sonorasaurus-thompsoni', 'Sonorasaurus thompsoni', 'ソノラサウルス', 'ソノラ砂漠のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'North America', 15, 12000),
  seed('dongbeititan-dongi', 'Dongbeititan dongi', 'ドンベイティタン', '北東の巨人', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Asia', 15, 10000),
  seed('limaysaurus-tessonei', 'Limaysaurus tessonei', 'リマイサウルス', 'リマイ川のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'South America', 15, 7000),
  seed('rinconsaurus-caudamirus', 'Rinconsaurus caudamirus', 'リンコンサウルス', 'リンコンのトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'South America', 11, 3500),
  seed('futalognkosaurus-dukei', 'Futalognkosaurus dukei', 'フタロンコサウルス', '巨人の首を持つもの', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'South America', 26, 50000),
  seed('notocolossus-gonzalezparejasi', 'Notocolossus gonzalezparejasi', 'ノトコロッスス', '南の巨大巨人', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'South America', 25, 60000),
  seed('lirainosaurus-astibiae', 'Lirainosaurus astibiae', 'リライノサウルス', 'リオハのトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Europe', 8, 2000),
  seed('ampelosaurus-atacis', 'Ampelosaurus atacis', 'アンペロサウルス', 'ぶどう畑のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Europe', 15, 8000),
  seed('turiasaurus-riodevensis', 'Turiasaurus riodevensis', 'トゥリアサウルス', 'トゥリアのトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Europe', 21, 30000),
  seed('brachytrachelopan-mesai', 'Brachytrachelopan mesai', 'ブラキトラケロパン', '短い首の羊飼い', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'South America', 10, 4000),
  seed('diamanthinasaurus-matildae', 'Diamantinasaurus matildae', 'ディアマンティナサウルス', 'ディアマンティナ川のトカゲ', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Australia', 15, 20000),
  seed('shingopana-songwensis', 'Shingopana songwensis', 'シンゴパナ', '広い首のもの', 'Saurischia', 'Sauropodomorpha', 'Herbivore', 'Africa', 13, 5000),

  seed('camptosaurus-dispar', 'Camptosaurus dispar', 'カンプトサウルス', '曲がるトカゲ', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'North America', 7.5, 1000),
  seed('mantellisaurus-atherfieldensis', 'Mantellisaurus atherfieldensis', 'マンテリサウルス', 'マンテルのトカゲ', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'Europe', 6, 900),
  seed('muttaburrasaurus-langdoni', 'Muttaburrasaurus langdoni', 'ムッタブラサウルス', 'ムッタブラのトカゲ', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'Australia', 8, 2500),
  seed('parksosaurus-warreni', 'Parksosaurus warreni', 'パルクソサウルス', 'パークスのトカゲ', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'North America', 2.5, 45),
  seed('gasparinisaura-cincosaltensis', 'Gasparinisaura cincosaltensis', 'ガスパリニサウラ', 'ガスパリニのトカゲ', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'South America', 1.7, 13),
  seed('rhabdodon-priscus', 'Rhabdodon priscus', 'ラブドドン', '棒状の歯', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'Europe', 4, 250),
  seed('zalmoxes-robustus', 'Zalmoxes robustus', 'ザルモクセス', '頑丈なザルモクシス', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'Europe', 3, 60),
  seed('orodromeus-makelai', 'Orodromeus makelai', 'オロドロメウス', '山を走るもの', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'North America', 2.4, 30),
  seed('jeholosaurus-shangyuanensis', 'Jeholosaurus shangyuanensis', 'ジェホロサウルス', '熱河のトカゲ', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'Asia', 1, 10),
  seed('haya-griva', 'Haya griva', 'ハヤ', '機敏なもの', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'Asia', 1.4, 20),
  seed('talenkauen-santacrucensis', 'Talenkauen santacrucensis', 'タレンカウエン', '小さな頭蓋骨', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'South America', 4, 300),
  seed('macrogryphosaurus-gondwanicus', 'Macrogryphosaurus gondwanicus', 'マクログリフォサウルス', '大きな謎のトカゲ', 'Ornithischia', 'Ornithopoda', 'Herbivore', 'South America', 6, 1000),
  seed('eolambia-caroljonesa', 'Eolambia caroljonesa', 'エオランビア', '夜明けのランベオサウルス類', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'North America', 6, 1000),
  seed('altirhinus-kurzanovi', 'Altirhinus kurzanovi', 'アルティリヌス', '高い鼻', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'Asia', 8, 2500),
  seed('probactrosaurus-gobiensis', 'Probactrosaurus gobiensis', 'プロバクトロサウルス', 'バクトロサウルス以前のもの', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'Asia', 6, 1000),
  seed('saurolophus-osborni', 'Saurolophus osborni', 'サウロロフス', 'トカゲのとさか', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'North America', 10, 3000),
  seed('kritosaurus-navajovius', 'Kritosaurus navajovius', 'クリトサウルス', '高貴なトカゲ', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'North America', 9, 2500),
  seed('shantungosaurus-giganteus', 'Shantungosaurus giganteus', 'シャントゥンゴサウルス', '山東の巨大なトカゲ', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'Asia', 14, 13000),
  seed('tsintaosaurus-spinorhinus', 'Tsintaosaurus spinorhinus', 'チンタオサウルス', '棘のある鼻', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'Asia', 10, 3000),
  seed('amurosaurus-riabinini', 'Amurosaurus riabinini', 'アムロサウルス', 'アムール川のトカゲ', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'Asia', 8, 2500),
  seed('brachylophosaurus-canadensis', 'Brachylophosaurus canadensis', 'ブラキロフォサウルス', '短い冠のトカゲ', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'North America', 9, 2500),
  seed('olorotitan-arharensis', 'Olorotitan arharensis', 'オロロティタン', '巨大な白鳥', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'Asia', 8, 3200),
  seed('magnapaulia-laticaudus', 'Magnapaulia laticaudus', 'マグナパウリア', '大きなパウルのもの', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'North America', 12, 10000),
  seed('hypacrosaurus-altispinus', 'Hypacrosaurus altispinus', 'ヒパクロサウルス', '高い棘を持つほぼ最高のトカゲ', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'North America', 9, 4000),
  seed('aralosaurus-tuberiferus', 'Aralosaurus tuberiferus', 'アラロサウルス', 'アラル海のトカゲ', 'Ornithischia', 'Hadrosauridae', 'Herbivore', 'Asia', 8, 3000),

  seed('diabloceratops-eatoni', 'Diabloceratops eatoni', 'ディアブロケラトプス', '悪魔の角の顔', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'North America', 5.5, 2000),
  seed('zuniceratops-christopheri', 'Zuniceratops christopheri', 'ズニケラトプス', 'ズニ族の角の顔', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'North America', 3.5, 200),
  seed('yinlong-downsi', 'Yinlong downsi', 'インロン', '隠れた竜', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'Asia', 1.2, 20),
  seed('saichania-chulsanensis', 'Saichania chulsanensis', 'サイカニア', '美しいもの', 'Ornithischia', 'Ankylosauria', 'Herbivore', 'Asia', 6.5, 2000),
  seed('pinacosaurus-grangeri', 'Pinacosaurus grangeri', 'ピナコサウルス', '板のトカゲ', 'Ornithischia', 'Ankylosauria', 'Herbivore', 'Asia', 5, 1800),
  seed('talarurus-plicatospineus', 'Talarurus plicatospineus', 'タラルルス', '編まれた尾', 'Ornithischia', 'Ankylosauria', 'Herbivore', 'Asia', 6, 2000),
  seed('polacanthus-foxii', 'Polacanthus foxii', 'ポラカントゥス', 'たくさんの棘', 'Ornithischia', 'Ankylosauria', 'Herbivore', 'Europe', 5, 2000),
  seed('sphaerotholus-goodwini', 'Sphaerotholus goodwini', 'スファエロトルス', '丸いドーム', 'Ornithischia', 'Pachycephalosauria', 'Herbivore', 'North America', 2, 40),
  seed('pachyrhinosaurus-lakustai', 'Pachyrhinosaurus lakustai', 'パキリノサウルス', '厚い鼻のトカゲ', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'North America', 6, 4000),
  seed('nasutoceratops-titusi', 'Nasutoceratops titusi', 'ナストケラトプス', '大きな鼻の角顔', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'North America', 4.5, 1500),
  seed('medusaceratops-lokii', 'Medusaceratops lokii', 'メドゥーサケラトプス', 'メドゥーサの角顔', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'North America', 6, 2000),
  seed('vagaceratops-irvinensis', 'Vagaceratops irvinensis', 'ヴァガケラトプス', 'さまよう角顔', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'North America', 4.5, 1200),
  seed('bagaceratops-rozhdestvenskyi', 'Bagaceratops rozhdestvenskyi', 'バガケラトプス', '小さな角顔', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'Asia', 1, 20),
  seed('xenoceratops-foremostensis', 'Xenoceratops foremostensis', 'クセノケラトプス', '異様な角顔', 'Ornithischia', 'Ceratopsia', 'Herbivore', 'North America', 6, 2500),
  seed('gargoyleosaurus-parkpinorum', 'Gargoyleosaurus parkpinorum', 'ガーゴイレオサウルス', 'ガーゴイルのトカゲ', 'Ornithischia', 'Ankylosauria', 'Herbivore', 'North America', 4, 1000),
  seed('minmi-paravertebra', 'Minmi paravertebra', 'ミンミ', 'ミンミの地名にちなむ', 'Ornithischia', 'Ankylosauria', 'Herbivore', 'Australia', 3, 300),
  seed('tuojiangosaurus-multispinus', 'Tuojiangosaurus multispinus', 'トゥオジャンゴサウルス', '多くの棘を持つトカゲ', 'Ornithischia', 'Stegosauria', 'Herbivore', 'Asia', 7, 4000),
  seed('dacentrurus-armatus', 'Dacentrurus armatus', 'ダケントルルス', '武装した尾の棘', 'Ornithischia', 'Stegosauria', 'Herbivore', 'Europe', 8, 5000),
  seed('giganspinosaurus-sichuanensis', 'Gigantspinosaurus sichuanensis', 'ギガントスピノサウルス', '巨大な棘のトカゲ', 'Ornithischia', 'Stegosauria', 'Herbivore', 'Asia', 4.2, 700),
];